//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MedProj.www.iugu_srv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="iugu_interopSoap", Namespace="http://tempuri.org/")]
    public partial class iugu_interop : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObterCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterSubscriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback NovoBoletoAsyncOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public iugu_interop() {
            this.Url = global::MedProj.www.Properties.Settings.Default.MedProj_www_iugu_srv_iugu_interop;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObterCustomerCompletedEventHandler ObterCustomerCompleted;
        
        /// <remarks/>
        public event ObterSubscriptionCompletedEventHandler ObterSubscriptionCompleted;
        
        /// <remarks/>
        public event NovoBoletoAsyncCompletedEventHandler NovoBoletoAsyncCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObterCustomer(string customerid, string clienteid, string email, string nome, string token) {
            object[] results = this.Invoke("ObterCustomer", new object[] {
                        customerid,
                        clienteid,
                        email,
                        nome,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObterCustomerAsync(string customerid, string clienteid, string email, string nome, string token) {
            this.ObterCustomerAsync(customerid, clienteid, email, nome, token, null);
        }
        
        /// <remarks/>
        public void ObterCustomerAsync(string customerid, string clienteid, string email, string nome, string token, object userState) {
            if ((this.ObterCustomerOperationCompleted == null)) {
                this.ObterCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterCustomerOperationCompleted);
            }
            this.InvokeAsync("ObterCustomer", new object[] {
                        customerid,
                        clienteid,
                        email,
                        nome,
                        token}, this.ObterCustomerOperationCompleted, userState);
        }
        
        private void OnObterCustomerOperationCompleted(object arg) {
            if ((this.ObterCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterCustomerCompleted(this, new ObterCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterSubscription", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ObterSubscription(string customerid, string token, out string msg) {
            object[] results = this.Invoke("ObterSubscription", new object[] {
                        customerid,
                        token});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ObterSubscriptionAsync(string customerid, string token) {
            this.ObterSubscriptionAsync(customerid, token, null);
        }
        
        /// <remarks/>
        public void ObterSubscriptionAsync(string customerid, string token, object userState) {
            if ((this.ObterSubscriptionOperationCompleted == null)) {
                this.ObterSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterSubscriptionOperationCompleted);
            }
            this.InvokeAsync("ObterSubscription", new object[] {
                        customerid,
                        token}, this.ObterSubscriptionOperationCompleted, userState);
        }
        
        private void OnObterSubscriptionOperationCompleted(object arg) {
            if ((this.ObterSubscriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterSubscriptionCompleted(this, new ObterSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NovoBoletoAsync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool NovoBoletoAsync(string customerId, string subscriptionId, System.DateTime vencimento, [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")] [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)] string[][] str_itens, PagadorVO vo, string boletoid, out string msg) {
            object[] results = this.Invoke("NovoBoletoAsync", new object[] {
                        customerId,
                        subscriptionId,
                        vencimento,
                        str_itens,
                        vo,
                        boletoid});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void NovoBoletoAsyncAsync(string customerId, string subscriptionId, System.DateTime vencimento, string[][] str_itens, PagadorVO vo, string boletoid) {
            this.NovoBoletoAsyncAsync(customerId, subscriptionId, vencimento, str_itens, vo, boletoid, null);
        }
        
        /// <remarks/>
        public void NovoBoletoAsyncAsync(string customerId, string subscriptionId, System.DateTime vencimento, string[][] str_itens, PagadorVO vo, string boletoid, object userState) {
            if ((this.NovoBoletoAsyncOperationCompleted == null)) {
                this.NovoBoletoAsyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNovoBoletoAsyncOperationCompleted);
            }
            this.InvokeAsync("NovoBoletoAsync", new object[] {
                        customerId,
                        subscriptionId,
                        vencimento,
                        str_itens,
                        vo,
                        boletoid}, this.NovoBoletoAsyncOperationCompleted, userState);
        }
        
        private void OnNovoBoletoAsyncOperationCompleted(object arg) {
            if ((this.NovoBoletoAsyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NovoBoletoAsyncCompleted(this, new NovoBoletoAsyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PagadorVO {
        
        private string ruaField;
        
        private string numeroField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string estadoField;
        
        private string paisField;
        
        private string cepField;
        
        private string cpfOuCnpjField;
        
        private string emailField;
        
        private string nomeField;
        
        private string foneField;
        
        private string dddField;
        
        /// <remarks/>
        public string rua {
            get {
                return this.ruaField;
            }
            set {
                this.ruaField = value;
            }
        }
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string cpfOuCnpj {
            get {
                return this.cpfOuCnpjField;
            }
            set {
                this.cpfOuCnpjField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string fone {
            get {
                return this.foneField;
            }
            set {
                this.foneField = value;
            }
        }
        
        /// <remarks/>
        public string ddd {
            get {
                return this.dddField;
            }
            set {
                this.dddField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObterCustomerCompletedEventHandler(object sender, ObterCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObterSubscriptionCompletedEventHandler(object sender, ObterSubscriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterSubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterSubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void NovoBoletoAsyncCompletedEventHandler(object sender, NovoBoletoAsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NovoBoletoAsyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NovoBoletoAsyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591